export const envName = {
  skill: 'VUE_APP_SKILL_TOKEN_CONTRACT_ADDRESS',
  cryptoblades: 'VUE_APP_CRYPTOBLADES_CONTRACT_ADDRESS',
  treasury: 'VUE_APP_TREASURY_CONTRACT_ADDRESS',
  quest: 'VUE_APP_SIMPLE_QUESTS_CONTRACT_ADDRESS',
  raid: 'VUE_APP_RAID_CONTRACT_ADDRESS',
  valor: 'VUE_APP_VALOR_TOKEN_CONTRACT_ADDRESS',
  market: 'VUE_APP_MARKET_CONTRACT_ADDRESS'
}
