name: Node.js Build
'on':
  workflow_dispatch: {}
  push: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - uses: actions/setup-node@v3
      with:
        node-version: '16.18.1'
    - name: Install Dependencies
      run: yarn install
      shell: bash
    - name: Build
      run: yarn build
      shell: bash
    - name: Publish
      uses: cloudflare/pages-action@1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: cbtracker
        directory: dist
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
permissions:
  id-token: write
  checks: write
  contents: read
  issues: write
  security-events: write
  pull-requests: write
